### ISSUE TITLE
Workflows for Dependent Resource - Umbrella Issue

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#1097]
`DependentResource`  serves as a building block of workflows of reconciling resources. Currently the managed dependent resources provides a limited way of expressing workflows - it's a list of resources what gets reconciled in defined order. Using standalone dependent resource in a reconciliation gives developers possibilities to use any java language constructs to describe arbitrary workflows (Think only conditionally create resource based in input resource values, or wait with API calls on a service until the deployment is not ready and things like that).

TODO:
- [x] Workflow design and related implementation in: https://github.com/java-operator-sdk/java-operator-sdk/issues/850
- [x] #1241
- [x] https://github.com/java-operator-sdk/java-operator-sdk/issues/1126
- [x] How fail fast / non fail fast approach should work with workflows, see also: #1107 
- [x] #1263
- [x] #1262

**Comment by csviri** [comment]
Note: workflows should handle explicit delete if a condition not hold.

**Comment by csviri** [comment]
Regarding workflows, I think this issue should fully cover it: https://github.com/java-operator-sdk/java-operator-sdk/issues/850

Will be simple enough, will be familiar for people working with Terraform or Cloudformation.

**Comment by csviri** [comment]
Added the topic of error handling, there was a discussion if in dependent resources reconciliation (`reconcile(...)` method call) should throw Exception or in the resource there should be and Error status in the result enum. Probably this part deserves it's own issue (will create one).

**Comment by cmoulliard** [comment]
That should be great to have part of the description an example. If the idea is to express like a `from-to-to` route, the flow of the dependent resources to be processed and their order, then adopting a DSL language could be a better idea than using Java annotations

Example: https://camel.apache.org/manual/java-dsl.html

WDYT ?@csviri

**Comment by csviri** [comment]
> That should be great to have part of the description an example. If the idea is to express like a `from-to-to` route, the flow of the dependent resources to be processed and their order, then adopting a DSL language could be a better idea than using Java annotations
> 
> Example: https://camel.apache.org/manual/java-dsl.html
> 
> WDYT ?@csviri

yes, that is a very good point, luckily we have actually both, see here in tests:
https://github.com/java-operator-sdk/java-operator-sdk/blob/4762be50af11fc0d085a3da635201b0074ea568f/operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowReconcileExecutorTest.java#L244-L252

or in a sample:
https://github.com/java-operator-sdk/java-operator-sdk/blob/4762be50af11fc0d085a3da635201b0074ea568f/sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageDependentsWorkflowReconciler.java#L46-L51

so the annotation is just a wrapper on an inner java-dsl. In other words in the backround the annoations will be transformed to the target model using this DSL. But both can be used at the end in an operator.
