### ISSUE TITLE
Dependent Resource MVP Scope

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#923]
This is an umbrella issue, that defines the scope of the initial release / minimal viable product of Dependent Resources:

- [x] #978
- [x] #977
- [x] Cleanup code and add missing unit and integration tests
- [x] #939 
- [x] https://github.com/java-operator-sdk/java-operator-sdk/issues/920
- [x] https://github.com/java-operator-sdk/java-operator-sdk/issues/924
- [x] #938
- [x] Check if it's possible to avoid creating the desired state if not needed (in particular, can we do the matching based only on the primary resource state instead of creating the desired state to compare it with the actual state)
- [x] `owned` state needs to be configured in `KubernetesDependentResource`. This was previously handled by `KubernetesDependentResourceController` but removing the logic from there where the configuration is available now makes it awkward to do (and is actually not done).
- [x] #940 
- [x] https://github.com/java-operator-sdk/java-operator-sdk/issues/948
- [x] (Optional, although quite beneficial to show the power of the feature) https://github.com/java-operator-sdk/java-operator-sdk/issues/870
- [x] #955
